name: fitness_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_splash_screen: ^1.0.4
  google_fonts: ^4.0.4
  provider: ^6.0.5
  carousel_slider: ^4.2.1
  liquid_swipe: ^3.1.0
  card_swiper: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/workoutClass/
    - assets/images/
